### Importeer de dataset

Voor deze opdracht gaan we werken met de Importeer de Iris dataset en print de eerste dataline met label

In [74]:
import numpy as np

# Scikit-learn: 
# Machine Learning in Python, Pedregosa et al., JMLR 12, pp. 2825-2830, 2011.
from sklearn.datasets import load_iris

# Iris dataset (Anderson, 1936; Fisher, 1936)
iris = load_iris()
X = iris.data
y = iris.target
print(f"{X[0]} {y[0]}")

print([f"Min: {np.min(X[:, i])} Max: {np.max(X[:, i])}" for i in range(X.shape[1])])


[5.1 3.5 1.4 0.2] 0
['Min: 4.3 Max: 7.9', 'Min: 2.0 Max: 4.4', 'Min: 1.0 Max: 6.9', 'Min: 0.1 Max: 2.5']


Als je de code hierboven runt zie je het resultaat van de print statement.

- Waar staan de getallen voor die je hier ziet? Wat zijn X en y?
X is de dataset met kenmerken van de bloemen. Y is een lijst met labels met welke bloem het is.

- Wat is de range van de getallen hier? Waarom?
['Min: 4.3 Max: 7.9', 'Min: 2.0 Max: 4.4', 'Min: 1.0 Max: 6.9', 'Min: 0.1 Max: 2.5'] - Dat zijn de min en max van de dataset.

### Labels one hot encoder

- In welke range zijn de labels nu (wat is de min/max waarde)?
- 0 tot 2, want er zijn 3 klassen (0, 1, 2)

- Zijn de waardes numeriek of eigenlijk nominaal? Waarom?
Nominaal, want de getallen zijn categorieen.

- Waarom willen we dit omzetten naar een ander formaat?  
Omdat een neuraal netwerk beter kan werken met numerieke data.

We willen de **labels** omzetten naar een formaat die een NN beter kan interpreteren. Gebruik hiervoor de OneHot Encoder. 

Maak eerst een **encoder** waarmee we de labels gaan encoden. 

In [75]:
from sklearn.preprocessing import OneHotEncoder

# One-hot encodeer de label
# sparse_output=False: resultaat na encoding is normale NumPy array
encoder = OneHotEncoder(sparse_output=False)

We willen de OneHotEncoder toepassen op de labels.
- Welke vorm heeft de lijst die de labels bevat? Print de lijst met labels.

In [76]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Als je nu probeert de data de HotEncode-en gaat er iets mis: 

    y = encoder.fit_transform( ..je labels hier..)

Dit komt doordat de labels nu in een lijstje zitten, terwijl fit_transform iets anders verwacht.

- Leg uit wat wel verwacht wordt?
fit_transform verwacht een 2d array, maar we hebben nu een 1d array.
    

Je kunt het probleem oplossen door een reshape functie toe te passen:

In [77]:
reshaped = y.reshape(-1, 1)

print hoe een gereshapete lijst eruit ziet. 

- Wat is er nu anders dan in de vorige representatie?
De lijst is nu een 2d array, met elke label in een aparte rij.

In [78]:
print(reshaped)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]


Converteer nu de label data naar OneHot encoded data. En print het eerste element. 

Hoe is label met oude waarde 1 nu geencodeerd?

*De label is nu een lijst met true of false waarden, waar de index van true overeenkomt met de waarde van het label. Bijvoorbeeld label 1 is nu [False, True, False]*

In [79]:
y_encoded = encoder.fit_transform(reshaped)
# print first label
print(y_encoded[0])

[1. 0. 0.]


### Split test /training set

**test_size** parameter geeft aan welk gedeelte van de gesplitte data naat de test set moet. De rest gaat naar training. De waarde ligt tussen 0 en 1.0. Welke waardse kies je?

*Ik wil graag 20% procent van de data gebruiken om te testen. Dus ik kies 0.2.*

**random_state** is de seed. Door deze vast te zetten kunnen we de splitsing reproduceren. Welke waarde kies jij?

*Ik kies 42, omdat dat een populair getal is in de programmeerwereld.*

Print de eerste dataline van de test en de trainingset met label (die je in de voorgaande stap al heb HotEncoded).

Print de vorm van de test en de training set (gebruik **.shape**).

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

### Simple NN: Layers opzet, architectuur

Gebruik keras van tensorflow om een neuraal netwerk op te zetten. De nieuwe manier om **keras** te gebruiken is:

    import tensorflow as tf
    model = tf.keras.Sequential([...])

Let op: voor sommigen zal de oude manier nog werken:


    from tensorflow import keras
    model = keras.Sequential([...])

Voeg de lagen van je neurale netwerk hier toe, dus tussen de blokhaken.
- Voeg de input layer toe. 

        tf.keras.Input(shape=(?,)),

Als parameter (?) kies het aantal input nodes. Hoeveel nodes kies je en waarom?

- Voeg nu een hidden layer toe. Je kunt volgende code gebruiken

        tf.keras.layers.Dense("?", activation=?)

- Kies als eerste parameter ("?") het aantal nodes in deze layer. Hoeveel nodes kies je? Waarom?

*Ik kies hier 10 nodes, omdat dat een goed getal is om het mee te proberen.*

- Kies de activation. Wat was activation ook al weer? Woor nu kun je gewoon de ***relu*** gebruiken.

*Activation is een functie die bepaalt of de neuron een waarde heeft of niet.*

- Je kunt nog meer hidden layers toevoegen. Hoeveel hidden layers voeg je toe? 

*Ik voeg er nog een toe, omdat het interresant is om te zien of hoe het netwerk reageert*

- Voeg nu de output layer toe. Code voor de output layer is hetzelfde als hidden, maar met een andere activatie functie. Hoeveel nodes kies je? Kies voor activation="softmax". Wat doet softmax ook al weer?

*Softmax is een kansschatting tussen de 0 en 1*


In [81]:
import tensorflow as tf


model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(4,)),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(3, activation="softmax")
])


### Compileer je model

Gebruik onderstaande code om je model te **compileren**

Wat compile doet: 

- Bepaalt hoe het model leert: adam optimizer
- Bepaalt wat het model probeert te minimaliseren: categorical crossentropy
- Bepaalt wat je wilt zien als prestatie‑indicator: 'accuracy' (bij ?)

Let er op dat je "loss" er niet bij hoeft te zetten omdat die zowieso als metric gebruikt wordt. 

- Wat is accuracy? Wat kun je er verdere bij zetten?

*Accurary is de verhouding van correct tot totaal aantal voorbeelden. Andere opties zijn precision, recall, en f1-score*

De dingen die je hier instelt worden pas later gebruikt, namelijk in de volgende stap - als je 

    .fit 

doet.

In [82]:

model.compile(optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])



### Model trainen

Nu gaan we het model trainen. Bepaal hoeveel epochs je wilt doen en eg hoe groot de batch grootte is.

- Wat zijn epochts?
Iteraties over de hele dataset.
- Wat is een batch hier?
Een batch is een subset van de dataset
- Zet de epochs en bach_ size op een bepaalde waarde. Hou verbose op 0.

- Wat als je verbose op 1 zet? Run de code weer.
Verbose logt informatie tijdens het trainen.

In [83]:
model.fit(X_train, y_train, epochs=200, batch_size=32, verbose=1)



Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1250 - loss: 1.2247  
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1333 - loss: 1.1855 
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1167 - loss: 1.1584 
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2333 - loss: 1.1357 
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2833 - loss: 1.1144 
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2917 - loss: 1.0961 
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3167 - loss: 1.0759 
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3500 - loss: 1.0586 
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4417 - loss: 1.0381 
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4750 - loss: 1.0203 
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5000 - loss: 1.0021 
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4833 - lo

### Maak voorspellingen

Nu kunnen we voorspellingen maken. Gebruik de functie 

    .predict()

Probeer het toe te passen op de eerste element uit X_test. Het kan zijn dat je dan een error krijgt. 

- Wat gaat hier mis? Hoe kunnen we het oplossen?

*Dit komt omdat de input niet in het juiste formaat is. Daarom moeten we de input vormen.*

**Hint: kijk naar de vorm van de argumenten die predict verwacht en wat je er aad doorgeeft**

- Welke klasse is nu voorspeld? Print het voorspelde klasse en de "echte" label uit de testset
De klasse die voorspeld is, is correct.

In [ ]:
import random


random_index = random.randint(0, len(X_test) - 1)

pred = model.predict(X_test[random_index].reshape(1, -1))
print(pred)
print(f"Voorspelde klasse: {np.argmax(pred)} vs {y_test[random_index]}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0.01301063 0.53381497 0.45317438]]
Voorspelde klasse: 1 vs [0. 1. 0.]


- Print nu de loss en de accuracy. Waarom wil je beide brinten en niet alleen de accuracy? 

*Omdat de loss aangeeft hoe goed het model presteert, accuracy geeft alleen aan hoeveel procent correct is. Als je een dataset met 95% van één waarde hebt, kan je een hoge accuracy hebben zonder dat het model echt goed is.*

- Wat gebeurt er als we verbose op 0 zetten?

*Geen informatie wordt gelogt tijdens het evalueren.*

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)
print(f'Test Accuracy: {accuracy:.2f}')


Test Accuracy: 0.93
